---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Copy Docker proxy environment file
  template:
    src: proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    owner: root
    group: root
    mode: 0644
    become: true
  when: docker_http_proxy is defined or docker_https_proxy is defined or docker_no_proxy is defined
  notify: restart docker
  become: true

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: true
  become: true
