---
- include_tasks: setup-RedHat.yml
  become: true
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  become: true
  when: ansible_os_family == 'Debian'

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: true
  become: true
