---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Add current user to docker group (not root user)
  user:
    name: "{{ ansible_user }}"
    group: docker
  when:
    - ansible_user != 'root'
    - docker_add_current_user_to_group | bool
  become: true

- name: Set Docker proxy
  include_tasks: set_proxy.yml
  when: (docker_http_proxy is defined) or (docker_https_proxy is defined)

- name: Ensure Docker is started and enabled at boot
  systemd:
    name: docker
    state: started
    enabled: true
  become: true
